import img1 from "../../public/assets/Web/1.jpg";
import img2 from "../../public/assets/Web/0.jpg";
import img3 from "../../public/assets/Web/2.png";
import img4 from "../../public/assets/Web/4.jpg";
import img5 from "../../public/assets/Web/5.jpg";
import img6 from "../../public/assets/Web/6.jpg";
import img7 from "../../public/assets/Web/7.png";
import img8 from "../../public/assets/Web/8.jpg";

export const Formations = [
  {
    id: "React - The Complete Guide (incl Hooks, React Router, Redux",
    status: true,
    category: "Web",
    name: "React - The Complete Guide (incl Hooks, React Router, Redux)",
    banner: img1,
    duration: 47,
    price: 229,
    students: 14,
    Tags: ["React", "React Hooks", "Javascript"],
    openSession: true,
    disc: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!",
  },
  {
    id: 1,
    category: "Web",
    name: "The Complete Web Developer Bootcamp",
    duration: 47,
    price: 229,
    banner: img2,
    Tags: ["Html", "CSS", "Javascript"],
    students: 14,
    openSession: true,
    disc: "Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!",
  },
  {
    id: 2,
    status: true,
    category: "Web",
    name: "Vue - The Complete Guide (w/ Router, Vuex, Composition API)",
    banner: img3,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["VueJS", "Vuex", "API"],
    openSession: true,
    disc: "Vue.js is an awesome JavaScript Framework for building Frontend Applications! VueJS mixes the Best of Angular + React!",
  },
  {
    id: 3,
    status: true,
    category: "Web",
    name: "Python and Django Full Stack Web Developer Bootcamp",
    banner: img4,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["Python", "Django", "Bootstrap"],
    openSession: true,
    disc: "Learn to build websites with HTML , CSS , Bootstrap , Javascript , jQuery , Python 3 , and Django!",
  },
  {
    id: 4,
    status: true,
    category: "Web",
    name: "Angular & NodeJS - The MEAN Stack Guide [2021 Edition]",
    banner: img5,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["Angular", "NodeJS", "Express", "MongoDB"],
    openSession: true,
    disc: "Learn how to connect your Angular Frontend to a NodeJS & Express & MongoDB Backend by building a real Application",
  },
  {
    id: 5,
    status: true,
    category: "Web",
    name: "MERN Stack Front To Back: Full Stack React, Redux & Node.js",
    banner: img6,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["ReactJS", "NodeJS", "Express", "MongoDB"],
    openSession: true,
    disc: "Learn how to Build and deploy a social network with Node.js, Express, React, Redux & MongoDB.",
  },
  {
    id: 6,
    status: true,
    category: "Mobile",
    name: "Flutter & Dart - The Complete Guide [2021 Edition]",
    banner: img7,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["Flutter", "Dart", "IOS", "Android"],
    openSession: true,
    disc: "A Complete Guide to the Flutter SDK & Flutter Framework for building native iOS and Android apps",
  },
  {
    id: 7,
    status: true,
    category: "Mobile",
    name: "Android Java Masterclass - Become an App Developer",
    banner: img8,
    duration: 47,
    price: 229,
    students: 10,
    Tags: ["Java", "Android Studio", "Android"],
    openSession: true,
    disc: "Improve your career options by learning Android app Development. Master Android Studio and build your first app today",
  },
];
